### ISSUE TITLE
Location type maps not showing on twenty-ten theme

### ISSUE THREAD

**Issue by Anterotesis** [CPHDH/placepress#8] opened 2020-12-18 18:26 UTC
The location type maps don't show on the Twenty-Ten theme.

See, for example: https://alsatia.org.uk/site/location-type/debtor-prison/

(They do work on Twenty-Eleven).

(I know it is an old theme, but it is still maintained, and if you don't wish to support it, it may be good to have a section in documentation listin g which themes work for this, and which don't.)

**Comment by ebellempire** [comment] 2020-12-18 18:34
This feature is working as intended (or at least as implemented). 

There is a note in the help menu on the settings page that describes how/when it works. 

<img width="1295" alt="Screen Shot 2020-12-18 at 1 29 37 PM" src="https://user-images.githubusercontent.com/441279/102648340-54fef800-4135-11eb-8980-f668ef2b515c.png">

Basically, the script needs something to hook into for placement on the page so it uses the category description, via [get_the_post_type_description()](https://developer.wordpress.org/reference/hooks/get_the_post_type_description/). So it won't work for themes that don't use that.

I'm open to alternative implementations.

**Comment by ebellempire** [comment] 2020-12-18 19:00
Added a further clarification on the settings page regarding theme compatibility. I'm going to close this for now.

**Closed by ebellempire** 2020-12-18 19:00 UTC
